GOOGLE_USER_MAIL = ""
GOOGLE_PASSWORD = ""
RESPONDER_NAME = ""

OPENAI_API_KEY = ""

FORM_BASE_URL = ""
FORM_VIEW_URL = FORM_BASE_URL + "/viewform"
FORM_FINISHED_URL = FORM_BASE_URL + "/formResponse"

PATH_TO_DRIVER = ""

PROMPT = ""
